# Generated by Django 3.1.6 on 2021-04-20 18:13

from django.db import migrations
from django.db import models
from orm import models as m


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(model_name='Companies',
                            name='or_podanie',
                            field=models.ManyToManyField('OrPodanieIssues')),
        migrations.AddField(model_name='Companies',
                            name='znizenie_imania',
                            field=models.ManyToManyField('ZnizenieImaniaIssues')),
        migrations.AddField(model_name='Companies',
                            name='likvidator_issues',
                            field=models.ManyToManyField('LikvidatorIssues')),
        migrations.AddField(model_name='Companies',
                            name='konkurz_vyrovnanie',
                            field=models.ManyToManyField('KonkurzVyrovnanieIssues')),
        migrations.AddField(model_name='Companies',
                            name='konkurz_restrukturalizacia',
                            field=models.ManyToManyField('KonkurzRestrukturalizaciaActors')),
    ]
