# Generated by Django 3.1.6 on 2021-04-23 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0001_initial'),
    ]

    operations = [
    ]
