# Generated by Django 3.1.6 on 2021-03-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='companies',
            fields=[
                ('cin', models.BigIntegerField(primary_key=True)),
                ('name', models.CharField(max_length=300, null=True)),
                ('br_section', models.CharField(max_length=50, null=True)),
                ('address_line', models.CharField(max_length=300, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('last_update', models.DateTimeField()),
            ],
        ),
    ]
